name: "PR Traduction"
description: "Translate the PR description"

inputs:
  GITHUB_TOKEN:
    description: "The GitHub token"
    required: true
  RAPID_API_KEY:
    description: "Rapid API key for Google Translate"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
